### ISSUE TITLE
It shows the same information for the inactive window (split) as the active one

### ISSUE THREAD

**Issue by ouuan** [ojroques/nvim-hardline#14]
![pic1](https://user-images.githubusercontent.com/30581822/117028303-2bcfb480-ad30-11eb-8476-aa4c5a76a275.png)

![pic2](https://user-images.githubusercontent.com/30581822/117028325-31c59580-ad30-11eb-8595-3282dc4614ca.png)

**Comment by ojroques** [comment]
Indeed. I had implemented a simple to check to prevent this issue and to avoid having recourse to autocommands but evidently it does not always work. I don't have time to work on this at the moment but in the following weeks I'll tackle it.

**Comment by ojroques** [comment]
I've improved how inactive window are kept track of. This issue should be solved but feel free to re-open it if you see the error again.

**Comment by renkam** [comment]
Looks like it is still broken. After switching tabs all the statuslines for splits contain the same information as the active window.
Also opening and closing tabs causes display errors. Opening tab not always show new tab, and closing a tab results in tab being still displayed.

**Comment by ouuan** [comment]
The wrong information in inactive windows is corrected when switching to that window, so it works correctly when manually opening a new window. For me, it only breaks when I use the diff mode.

**Comment by ojroques** [comment]
Thanks for the report, I've fixed the tab behavior in the latest commit.

**Comment by ouuan** [comment]
It still doesn't work for me in diff mode: `nvim -d <file1> <file2>`.

**Comment by ojroques** [comment]
@ouuan your issue and all other corner cases should be fixed in the latest commit now. Basically I've changed the way statuslines get redrawn in each window.
